name: deonnajanone
favicon: null
layout_spectrum: 0.2038620701059699
typography_spectrum: 0.5899011702276766
title: Deonna Janone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7642505110707134
  lightness: 0.34547614702023566
  saturation: 0.11085789930075407
  rhythmicContrast: 0.8125467787031084
purpose: []
